# Molecular dynamics in Python: NumPy is great

In this workshop you'll write a molecular dynamics simulator of a 3-dimensional system using NumPy. Ideally you will have written a simulator using lists, and will be able to appreciate the differences between the types.

If you feel you need a refresher or reference to keep up with all the Python being thrown around, there is a short summary in `00_basics_of_python.ipynb`.

If you've skipped to here without doing `01_molecular_dynamics_1D.ipynb`, a lot of the molecular dynamics theory is laid out there and commented out here to save space. If something is unclear, try checking out the corresponding section in that notebook. Equations and such will still be provided here.

If you're having trouble with an error message, Googling the message is usually the fastest way to a solution. Results from StackOverflow are particularly helpful.

 The colour-coding here is as follows:

<div class="alert alert-block alert-warning">

**Tip**

Python tip.</div>

<div class="alert alert-block alert-success">&#x1F40D;  &nbsp; Explanation of previous Python &nbsp; &#x1F40D; </div>

<div class="alert alert-block alert-info"><b>To do</b></div>

Often I will give suggestions of Numpy methods to use. These can take two forms:

1. *np.function().* This is a function of Numpy you can call with that syntax. These will often have required or useful arguments that you can specify, and lookup via Google.
2. *ndarray.function().* This is a method of the Numpy.ndarray class. These functions should be called from your array, e.g. `my_array.function()`. 

## NumPy

NumPy arrays are multidimensional arrays of **a single** type. They act like lists, but with much less memory overhead and more analysis functionality. Numpy arrays are great for analysing regular data of one particular type.

One downside is that it is expensive to change the size of an array once created, as it requires a copy. 

Generally numpy is imported as np. Below is a brief refresher on NumPy -- there's a longer one in the `00_basics_of_python.ipynb`. There's also a file called the `Numpy_Python_Cheat_Sheet.pdf` that's a handy guide.

In [1]:
import numpy as np

In [32]:
# convert lists to arrays with np.array
arr = np.array([[1, 2, 3], [7, 8, 9], [12, 6, 10], [4, 7, 9.1]])
arr

array([[ 1. ,  2. ,  3. ],
       [ 7. ,  8. ,  9. ],
       [12. ,  6. , 10. ],
       [ 4. ,  7. ,  9.1]])

In [5]:
arr.shape # shape of matrix (rows, columns)

(4, 3)

In [6]:
arr[0] # first row

array([1., 2., 3.])

In [10]:
# reshape arrays
arr_reshaped = arr.reshape(2, 3, 2) # must multiply to same number of elements as before
print(arr_reshaped.shape)
arr_reshaped

(2, 3, 2)


array([[[ 1. ,  2. ],
        [ 3. ,  7. ],
        [ 8. ,  9. ]],

       [[12. ,  6. ],
        [10. ,  4. ],
        [ 7. ,  9.1]]])

In [11]:
arr[0] # first sub-array

array([1., 2., 3.])

### Vectorisation

Vectorisation is a fundamental feature of NumPy. Vectorised operations is the art of replacing loops such as those in your 1D simulator with array expressions. These expressions delegate expensive Python loops to optimised C or Fortran code, and are often one or two orders of magnitude faster than the equivalent Python. <a href="https://www.safaribooksonline.com/library/view/python-for-data/9781449323592/ch04.html?orpq"> [Read more]</a>

In [60]:
rand_arr = np.random.rand(500) # returns an array of shape (500,) with random floats from 0 to 1
rand_arr

array([0.75914817, 0.56047993, 0.17573219, 0.7601628 , 0.05014488,
       0.13242088, 0.62746246, 0.23486989, 0.14119836, 0.4870502 ,
       0.33792227, 0.05618971, 0.65809361, 0.81668483, 0.03057128,
       0.01619732, 0.07022853, 0.47244585, 0.40713241, 0.95199234,
       0.43954637, 0.52660916, 0.15505784, 0.23762716, 0.42750811,
       0.85892172, 0.57576837, 0.44028106, 0.05651255, 0.39686091,
       0.94882739, 0.34108872, 0.81779561, 0.35323934, 0.50353761,
       0.28505411, 0.03031799, 0.00996828, 0.4606337 , 0.81753994,
       0.89089814, 0.17284921, 0.37127743, 0.42432509, 0.50500481,
       0.58730686, 0.70476958, 0.08203985, 0.76440471, 0.22090578,
       0.50534483, 0.19347294, 0.93368919, 0.5473222 , 0.1733516 ,
       0.18834162, 0.5571452 , 0.57596044, 0.07773079, 0.87846705,
       0.56199715, 0.71241701, 0.10875048, 0.50034852, 0.32205723,
       0.56326755, 0.07745548, 0.68104011, 0.20455296, 0.929815  ,
       0.6940555 , 0.95190222, 0.03833058, 0.77618144, 0.27528

In [26]:
def count_under_half(x):
    """Count how many numbers are under 0.5"""
    counter = 0
    for i in x:
        if i < 0.5:
            counter += 1
    return counter

def vectorised_count(x):
    return np.count_nonzero(x<0.5)

#### &#x1F40D;  &nbsp; What's happening here? &nbsp; &#x1F40D; 

It's not immediately obvious how `np.count_nonzero(x<5)` works. This one-liner takes advantage of the concept of 'truthiness' in Python. `x < 0.5` returns a boolean matrix on whether this inequality is satisfied (try it below).

In [61]:
rand_arr < 0.5

array([False, False,  True, False,  True,  True, False,  True,  True,
        True,  True,  True, False, False,  True,  True,  True,  True,
        True, False,  True, False,  True,  True,  True, False, False,
        True,  True,  True, False,  True, False,  True, False,  True,
        True,  True,  True, False, False,  True,  True,  True, False,
       False, False,  True, False,  True, False,  True, False, False,
        True,  True, False, False,  True, False, False, False,  True,
       False,  True, False,  True, False,  True, False, False, False,
        True, False,  True, False,  True, False, False,  True, False,
        True,  True,  True, False,  True,  True,  True,  True, False,
        True, False,  True,  True, False, False,  True, False, False,
        True,  True, False,  True, False,  True,  True, False, False,
       False,  True, False,  True,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True, False, False, False,
       False,  True,

`np.count_nonzero` then counts all the 'truthy' values -- those that Python evaluates to True or False. For example, any non-zero numbers will evaluate to True. 0, an empty list or dictionary, and None are considered 'falsy'. You can check what is truthy or falsy by calling `bool` on an object.

In [69]:
bool(-4.2)

True

In [70]:
bool(0)

False

In [71]:
int(True) # True is equivalent to 1

1

#### &nbsp; <a class="tocSkip">

In [31]:
count_under_half(rand_arr) == vectorised_count(rand_arr)

True

In [28]:
%timeit count_under_half(rand_arr)

51.7 µs ± 733 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [29]:
%timeit vectorised_count(rand_arr)

968 ns ± 4.17 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### Broadcasting

Broadcasting is another important part of NumPy, and they have a <a href="https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html"> very informative page on it here.</a> Essentially, NumPy will try to align arrays when operations are performed between them, like the picture below. 
<img src="files/broadcasting.jpg" width="500px">

Scalars are just treated as having 1 dimension. 

In [86]:
arr + 2

array([[  1. ,   0. ,  -1. ],
       [ -5. ,  -6. ,  -7. ],
       [-10. ,  -4. ,  -8. ],
       [ -2. ,  -5. ,  -7.1]])

In [34]:
arr ** 3  # Cube every element

array([[1.00000e+00, 8.00000e+00, 2.70000e+01],
       [3.43000e+02, 5.12000e+02, 7.29000e+02],
       [1.72800e+03, 2.16000e+02, 1.00000e+03],
       [6.40000e+01, 3.43000e+02, 7.53571e+02]])

In [35]:
arr *= -1 # Operations like +=, -=, etc work on arrays too
arr

array([[ -1. ,  -2. ,  -3. ],
       [ -7. ,  -8. ,  -9. ],
       [-12. ,  -6. , -10. ],
       [ -4. ,  -7. ,  -9.1]])

In [40]:
arr + [1, 0, 1]  # Will convert to an array

array([[  0. ,  -2. ,  -2. ],
       [ -6. ,  -8. ,  -8. ],
       [-11. ,  -6. ,  -9. ],
       [ -3. ,  -7. ,  -8.1]])

In [41]:
arr + [0, 1]  # Will give an error!

ValueError: operands could not be broadcast together with shapes (4,3) (2,) 

In [42]:
arr + arr  # Elementwise addition (equivalent to arr * 2)

array([[ -2. ,  -4. ,  -6. ],
       [-14. , -16. , -18. ],
       [-24. , -12. , -20. ],
       [ -8. , -14. , -18.2]])

In [43]:
# .T returns the transpose of the matrix
arr @ arr.T # @ returns the dot product

array([[ 14.  ,  50.  ,  54.  ,  45.3 ],
       [ 50.  , 194.  , 222.  , 165.9 ],
       [ 54.  , 222.  , 280.  , 181.  ],
       [ 45.3 , 165.9 , 181.  , 147.81]])

### Axes

In NumPy, an axis is a dimension of a multidimensional array. They are indexed from 0, along the sequence returned by `arr.shape`. It's important to keep these straight for operations that 'collapse' axes, such as `sum`.

In [83]:
arr.shape # first axis has 4 elements

(4, 3)

In [80]:
arr.sum() #  default: sum along all the axes. Equivalent to arr.sum(axis=(0, 1))

-78.1

In [81]:
arr.sum(axis=0)

array([-24. , -23. , -31.1])

Calling `sum` with the argument `axis=0` applies `sum` along the axis that is collapsed, returning an array of three elements. `axis` can take a tuple argument, in which case it will collapse along all the axes specified.

In [84]:
arr.sum(axis=1)

array([ -6. , -24. , -28. , -20.1])

### Indexing

NumPy arrays can be indexed and sliced pretty much like lists. `:` is the slice operator. The full slice notation is `i:j:k` where `i` is the starting index (inclusive), `j` is the ending index (exclusive), and `k` is the step. The following are valid slices. <a href="https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.indexing.html"> [Read more] </a>

In [46]:
arr[:]  # Select all

array([[ -1. ,  -2. ,  -3. ],
       [ -7. ,  -8. ,  -9. ],
       [-12. ,  -6. , -10. ],
       [ -4. ,  -7. ,  -9.1]])

In [49]:
arr[1:] # i=1, from second element onwards

array([[ -7. ,  -8. ,  -9. ],
       [-12. ,  -6. , -10. ],
       [ -4. ,  -7. ,  -9.1]])

In [50]:
arr[1:3] # i=1, j=3, second to third elements

array([[ -7.,  -8.,  -9.],
       [-12.,  -6., -10.]])

In [52]:
arr[1::3] # from second element on, every third element

array([[-7., -8., -9.]])

Commas separate dimensions.

In [44]:
arr[:, 0] # first column

array([ -1.,  -7., -12.,  -4.])

In [45]:
arr[1, 0] # element in second row, first column

-7.0

Unlike lists, NumPy offers advanced indexing (or fancy indexing) with sequences such as lists or other arrays. You can use two types to index: integers (as before), or booleans.

In [56]:
arr[[1,3]]

array([[-7. , -8. , -9. ],
       [-4. , -7. , -9.1]])

In [58]:
arr[[True, False, False, True]]

array([[-1. , -2. , -3. ],
       [-4. , -7. , -9.1]])

This can be super useful and it's one of my favourite things about NumPy! It can be used to access, or modify, values that satisfy a condition.

In the vectorisation section, I counted up the numbers under 0.5 in `rand_arr` with this one-liner:
```
def vectorised_count(x):
    return np.count_nonzero(x<0.5)
```

`x<0.5` returns a boolean matrix. If I indexed `rand_arr` with this instead, I would get all the values:

In [72]:
rand_arr[rand_arr<0.5]

array([0.17573219, 0.05014488, 0.13242088, 0.23486989, 0.14119836,
       0.4870502 , 0.33792227, 0.05618971, 0.03057128, 0.01619732,
       0.07022853, 0.47244585, 0.40713241, 0.43954637, 0.15505784,
       0.23762716, 0.42750811, 0.44028106, 0.05651255, 0.39686091,
       0.34108872, 0.35323934, 0.28505411, 0.03031799, 0.00996828,
       0.4606337 , 0.17284921, 0.37127743, 0.42432509, 0.08203985,
       0.22090578, 0.19347294, 0.1733516 , 0.18834162, 0.07773079,
       0.10875048, 0.32205723, 0.07745548, 0.20455296, 0.03833058,
       0.2752828 , 0.24437383, 0.38482537, 0.17324056, 0.4595164 ,
       0.44218605, 0.27776626, 0.49948259, 0.10925191, 0.01660572,
       0.20922387, 0.15593267, 0.4744402 , 0.44009835, 0.47942167,
       0.22208255, 0.11991731, 0.31096392, 0.2712153 , 0.0119902 ,
       0.02982121, 0.03425661, 0.04965785, 0.20790462, 0.17191359,
       0.21274909, 0.16207841, 0.25040975, 0.3403576 , 0.38078327,
       0.04905407, 0.04527376, 0.12820822, 0.21523658, 0.06530

And because indexing can also assign values, I can modify them:

In [73]:
rand_arr[rand_arr<0.5] += 10
rand_arr

array([ 0.75914817,  0.56047993, 10.17573219,  0.7601628 , 10.05014488,
       10.13242088,  0.62746246, 10.23486989, 10.14119836, 10.4870502 ,
       10.33792227, 10.05618971,  0.65809361,  0.81668483, 10.03057128,
       10.01619732, 10.07022853, 10.47244585, 10.40713241,  0.95199234,
       10.43954637,  0.52660916, 10.15505784, 10.23762716, 10.42750811,
        0.85892172,  0.57576837, 10.44028106, 10.05651255, 10.39686091,
        0.94882739, 10.34108872,  0.81779561, 10.35323934,  0.50353761,
       10.28505411, 10.03031799, 10.00996828, 10.4606337 ,  0.81753994,
        0.89089814, 10.17284921, 10.37127743, 10.42432509,  0.50500481,
        0.58730686,  0.70476958, 10.08203985,  0.76440471, 10.22090578,
        0.50534483, 10.19347294,  0.93368919,  0.5473222 , 10.1733516 ,
       10.18834162,  0.5571452 ,  0.57596044, 10.07773079,  0.87846705,
        0.56199715,  0.71241701, 10.10875048,  0.50034852, 10.32205723,
        0.56326755, 10.07745548,  0.68104011, 10.20455296,  0.92

This will be very useful when you are deciding which inter-particle interactions to consider for calculating forces and energies below.

## Python

### Class definition

<div class="alert alert-block alert-info">

<b>Define the class `MD3D` below. </b>
</div>

<!--Several properties are defined in `__init__`, such as the length of the system. This is required as MD is still a slow process and only a finite system can be simulated in a finite cell. An infinite system is approximated by tiling identical cells, as in the image below. The computer only keeps track of the central one in bold, and particle interactions are only computed between the closest image. -->

You'll need to set up containers to keep track of the coordinates, velocities, forces, temperatures, and energies of the system. *With NumPy arrays you must decide the size at creation, as you can't append to the same object as you can with lists.* Coordinates, velocities, and forces should each have 3 dimensions for their components in the x, y, and z directions. They should also track every particle, and every time-step. Your arrays will likely look like the below:

<img src="files/matrix.png" width="500px">


Of course, your coordinate array should have 1 extra time-step to account for the positions at negative time that we will define here, just like `01_molecular_dynamics_1D.ipynb`.

The temperature and energy arrays are much simpler, as there is only one temperature and one energy for each time-step. 

Again, we will initialise the system with forces of 0.0 and random velocities.



<div class="alert alert-block alert-warning">

**Tip**

Useful `numpy` functions might include:
- np.zeros()
- np.random.rand()
</div>

In [1]:
import numpy as np

class MD3D:
    n_dims = 3 # dimension of box
    
    def __init__(self, n_steps, box_length = 36.0, n_particles=36):
        
        self.n_particles = n_particles # number of particles
        self.cell = np.array([box_length, box_length, box_length]) # cell for periodic boundary conditions
        
        self.time_step = 0.01  # integration time step
        self.n_steps = n_steps  # number of steps to take
        
        self.cutoff_dist = 18.0  # distance cutoff for computing interactions
        self.cutoff_sq = self.cutoff_dist ** 2
        self.cutoff_energy =  4 * (self.cutoff_dist ** -12 - self.cutoff_dist ** -6)
        
        self.temperature = 0.728
        
        # Define numpy arrays for coordinates,
        # velocities, forces, temperatures, 
        # and energies
        self.xyz = np.zeros((n_steps + 1, n_particles, 3))
        self.velocities = np.random.rand(n_steps, n_particles, 3)
        self.forces = np.zeros((n_steps, n_particles, 3))
        self.temperatures = np.zeros(n_steps)
        self.energies_potential = np.zeros(n_steps)
        self.energies_total = np.zeros(n_steps)
    

####  &#x1F40D;  &nbsp; What's happening here? &nbsp; &#x1F40D; 

<div class="alert alert-block alert-success">
    
    
It is common to import packages with abbreviated names. The standard alias for numpy as np. Importing numpy as np means that the classes and methods of Numpy can be accessed through `np`, but not through `numpy`. `np.zeros()` would call the the `zeros` function of numpy, whereas `numpy.zeros()` would result in an error.
</div>

#### &nbsp;

<div class="alert alert-block alert-info"><b>

Create an instance of `MD3D` below and assign it to a variable. Check that the arrays you created look how you expected them to. (You can look at the shape of an array with `ndarray.shape`).</b></div>

### Set up initial state

In the function `setup_system` you should set up your simulation system at time=0. 

Previously, this involved the following steps for each particle:

1. Generating initial coordinates
2. Generating an initial force (0.0 to start off)
3. Generating an initial velocity (random to start with)
4. Scaling your random velocities to match your desired temperature `self.temperature`
5. Generating 'previous' coordinates for each particle for time=-`self.time_step` based on those scaled velocities

However, if you used `np.zeros()` and `np.random.rand()` before, you have already defined your initial forces and velocities. Therefore all that is required steps 1, 4, and 5.

As before, the scale factor $s$ can be calculated from the sum of squared velocities over the number of particles $V_\sigma$, and the temperature $T$:

$$s = n_{dim}*\sqrt{\frac{T_0}{V_\sigma}}$$

As before, the previous x-coordinates can be calculated:
$$x_{prev} = x_{now} - v_{now}*\Delta t$$

#### <div class="alert alert-block alert-info"><b>Write a function that returns the scale factor as defined above.</b></div>

In [2]:
def get_scale_factor(avg_vsum_sq, temperature):
    return (3 * temperature / avg_vsum_sq) ** 0.5

<div class="alert alert-block alert-info">
<b>
    1. Write a function get_xyz to generate atom positions. <br>
    2. Use indexing to replace the the elements in your coordinate array with the appropriate positions.<br>
    3. Calculate the previous xyz coordinates.<br>
</b></div>

In [69]:
def get_xyz(md):
    idx = np.array(range(md.n_particles)) + 0.5
    return idx.reshape(-1, 1) * md.cell/md.n_particles

<div class="alert alert-block alert-warning">
    
**Tip**

Useful `numpy` functions might include:
- ndarray.sum()
</div>

In [72]:
def setup_system(md):
        """
        Initialise system properties at time=0.
        """
        # generate current coordinates
        md.xyz[0] = get_xyz(md)
        
        avg_sum = md.velocities[0].sum() / md.n_particles # sum of velocities at time 0 / n_particles
        avg_sum_sq = (md.velocities[0] ** 2).sum()/md.n_particles  # calculate the sum of squared velocities at time 0 over n_particles
        
        scale_factor = get_scale_factor(avg_sum_sq, md.temperature)
        
        # Rescale velocities and generate previous x coordinates 
        md.velocities[0] = (md.velocities[0] - avg_sum) * scale_factor
        md.xyz[-1] = md.xyz[0] - md.velocities[0] * md.time_step
        

####  &#x1F40D;  &nbsp; What's happening here? &nbsp; &#x1F40D;

<div class="alert alert-block alert-success">


In the cell above, coordinates for time=0 are generated and assigned to `md.xyz[0]`, ie the first position. Coordinates for the negative time before that are also calculated and are assigned to `md.xyz[-1]`. Indexing in arrays is a modular, and `x[-1]` will return the last element of `x`. 
<p>

Of course it doesn't make physical sense to have the earliest coordinates as the last element of the array. Instead, for every time-step `i` we could remember that the coordinates array should be `i+1` to account for the extra step. Alternatively, we could just add an extra but ignored time-step to the velocities, forces, energies and temperatures array. Out of these three approaches I personally find that this is the most convenient. As long as we remember to truncate the array to the second-last element before we output our results, this is a harmless shortcut. 
</div>

#### &nbsp;
<div class="alert alert-block alert-info">

<b>Call setup_system on your instance of `MD1D` and check that: <ul>
        <li> your velocities at time=0 are now different
        <li> your coordinates in the first element and the last element are now not zero 
 </b>
        </div>

In [95]:
setup_system(MD3D(100))

### Calculating energies and forces

As before, the function `get_forces` is responsible for calculating the force between each particle pair within your `self.cutoff_dist` cutoff, and the total energy of the system at the time. The end result is.

For a Lennard-Jones system in reduced units, the energy $E_{LJ}$ can be defined as:

$$
\begin{equation}
E^{LJ}(r_{ij}) = 4\big[r^{12} - r^6\big]
\end{equation}$$

and the force $f_x$ is defined as:

$$
f_x(r) = \frac{48x}{r^2}\big(\frac{1}{r^{12}}-0.5\frac{1}{r^6}\big)
$$


#### <div class="alert alert-block alert-info"><b>Using the equation above, write functions to calculate the energy and force between two atoms as a function of distance.</b></div>

In [121]:
def calculate_energy(sq_dist):
    d6_inv = 1/sq_dist ** 3
    return 4 * d6_inv * (d6_inv - 1)

In [122]:
def calculate_force(sq_dist):
    d2_inv = 1/sq_dist
    d6_inv = d2_inv ** 3
    return 48 * d2_inv * d6_inv * (d6_inv - 0.5)

#### <div class="alert alert-block alert-info"><b>Write a function to calculate energies and forces for time-step $i$.</b></div>

There are a few approaches you could take. This function has to check the distance between every particle and every particle, and compare that to the `cutoff_dist` before possibly computing the energy and forces -- with as few loops as possible.

The approach detailed below unfortunately only gets rid of one loop, but it is much less abstract than the fully vectorised version. An explanation of the vectorised approach in Part 1.5.

#### Naive Numpy approach: Looping over particles once

```
for i in range(md.n_particles-1): # for every particle except the last
    for j in range(i+1, md.n_particles): # for every particle from i onwards
```
The 1D version had nested for loops, as in the code above. This approach keeps the outside loop but uses vectorised operations instead of the inside one, speeding it up significantly. For each particle `i`, you can calculate the vector displacements to other particles as an Nx3 array like below.

<img src="files/n_particles.png" width="400px">

Then calculate the squared distance, remembering that 
$$ d(\vec{i},\vec{j}) = \sqrt{(i_x-j_x)^2 + (i_y-j_y)^2 + (i_z-j_z)^2}$$

You should end up with an Nx1 array.
<img src="files/sq_dist.png" width="400px">

Remember that Python can evaluate relationships such as `arr < 1` and return a boolean matrix that you can use to access or modify the array.
<img src="files/indexing.png" width="400px">

#### &nbsp;

In [129]:
def get_forces(md, step):
    """Calculating energy and force"""
    for i in range(md.n_particles-1):
        distance = md.xyz[step][i+1:] - md.xyz[step][i]
        n_cells = md.cell * np.round_(distance/md.cell)
        min_distance = distance - n_cells
        
        sq_dist = (min_distance ** 2).sum(axis=1, keepdims=True)
        
        ff = calculate_force(sq_dist)
        en = calculate_energy(sq_dist) - md.cutoff_energy

        forces = np.where(sq_dist < md.cutoff_sq, ff, 0)
        energy = np.where(sq_dist < md.cutoff_sq, en, 0)
        md.forces[step][i] += forces.sum(axis=0)
        md.forces[step][i+1:] -= forces
        
        md.energies_potential[step] += energy.sum()
        

#### <div class="alert alert-block alert-info"><b>Run get_forces on your `MD3D` instance and check that there are no errors.</b></div>

### Integrating equations of motion

Now that the forces have been computed, we can integrate the equations of motion. 

The estimate of the position at the next time-step is calculated from the current properties below, where $f(t)$ represents the force at time $t$. $t + \Delta t$ and $t - \Delta t$ represent the next and previous time-steps respectively. 
$$
x(t + \Delta t) \approx 2x(t) - x(t - \Delta t) + f(t) \Delta t^2
$$

The velocity of the current time-step can therefore be calculated:
$$
v(t) = \frac{x(t + \Delta t) - x(t - \Delta t)}{2 \Delta t}
$$

We use this to calculate the instantaneous temperature by the equation above:

$$T(t) = \sum\limits_{i=1}^{N} \frac{v^2_{i}(t)}{N \times n_{dims}}$$


We would also like to calculate the total energy per particle. This energy is a sum of the potential energy and kinetic energy. The potential energy was calculated in the `get_forces` function using the Lennard-Jones potential. The kinetic energy is calculated with $\frac{1}{2}mv^2$. In reduced units, this simplifies to $\frac{1}{2}v^2$.

#### &#x1F4DC;  &nbsp; Background behind equations &nbsp; &#x1F4DC;

The Taylor expansion of the particle coordinate at time $t$ gives:
    
$$
\begin{eqnarray}
    x(t + \Delta t) &=& x(t) + \dot x(t) \Delta t + \ddot x(t)\frac{\Delta t^2}{2!} + \dddot x(t)\frac{\Delta t^3}{3!} + \mathcal{O}(\Delta t^4) \\
    x(t - \Delta t) &=& x(t) - \dot x(t) \Delta t + \ddot x(t)\frac{\Delta t^2}{2!} - \dddot x(t)\frac{\Delta t^3}{3!} + \mathcal{O}(\Delta t^4)
\end{eqnarray}
$$
    
   Adding those equations together and substituting acceleration $a(t) = \ddot x(t)$ results in this:
   
   
   $$
   x(t + \Delta t) + x(t - \Delta t) = 2x(t) + a(t)\Delta t^2 + \mathcal{O}(\Delta t^4)
   $$
   
   Given that mass $m$ vanishes in reduced units, the force $F=ma$ reduces to $F=a$. The remainder term $\mathcal{O}(\Delta t^4)$ is dropped as the error. Therefore:
   
$$
\begin{eqnarray}
x(t + \Delta t) + x(t - \Delta t) &=& 2x(t) + f(t)\Delta t^2 \\
x(t + \Delta t) &\approx& 2x(t) - x(t - \Delta t) + f(t) \Delta t^2
\end{eqnarray}
$$



This method uses forces to compute the new positions. The velocity at time $t$ is approximated when positions at time-steps before and after $t$ are known, using the equation in the main block above. Known as the Verlet algorithm, this approach is more accurate than the Euler method of using the velocity at time $t$ to determine the position at time $t + \Delta t$.

</div>

#### <div class="alert alert-block alert-info"><b>Using the equations above, write a function to integrate the equations of motion.</b></div>

In [27]:
def next_position(current_xyz, previous_xyz, time_step, current_force):
    x = 2 * current_xyz - previous_xyz + time_step * time_step * current_force
    return x

def current_velocity(next_xyz, previous_xyz, time_step):
    v = (next_xyz - previous_xyz) / (2 * time_step)
    return v

def instant_temperature(vsum_sq, n_particles):
    return vsum_sq / n_particles

def total_energy_per_particle(energy, vsum_sq, n_particles):
    total_energy = energy + (0.5 * vsum_sq)
    return total_energy / n_particles

In [28]:
def integrate(md, step):
    """Integrate equations of motion"""
    
    # As a vectorised array operation, 
    # calculate the next positions with next_position()
    # and current velocity and current_velocity()
    md.xyz[step+1] = next_position(md.xyz[step], md.xyz[step-1], md.time_step, md.forces[step]) 
    md.velocities[step] = current_velocity(md.xyz[step+1], md.xyz[step-1], md.time_step)
    
    # Square the velocities and sum them to
    # get vsum_sq
    vsum_sq = (md.velocities[step] ** 2).sum()
    
    # calculate the instantaneous temperature and append 
    # it to md.temperatures
    md.temperatures[step] = instant_temperature(vsum_sq, md.n_particles)
    md.energies_total[step] = total_energy_per_particle(md.energies_potential[step], vsum_sq, md.n_particles)
    print("  --- Energy: {en} ---".format(en=md.energies_total[step]))

### Viewing

<div class="alert alert-block alert-info"><b>
    Now you need to write out your coordinates to a file that's readable by other software. Use string formatting to write a file that looks like the example 'example.xyz' in the folder.</b>
<div class="alert alert-block alert-warning">
    
   **Tip**
   
   `range(x)` returns an iterable of numbers `(0, 1, 2, ... x-1)`. 
   
   File I/O is usually handled within context managers that automatically close the file when you're done. To read:
   
   ```
       with open(filename, 'r') as f:
           contents = f.read()
   ```
   
   To write:
   ```
       with open(filename, 'w') as f:
           f.write(contents)
   ```
   
   `'\n'` prints a newline, i.e. moves to the next line in the file. I would expect `f.write("e\nb  c\n  d")` to write:
   
   ```
   e
   b  c
     d
   ```
</div>
</div>

In [107]:
def write_coordinates(md):
    # x[y:] take all elements in x from index y onwards
    x_coords = md.xyz[:-1] # remove last column with negative time
    with open('example3d.xyz', 'w') as f: # f is the open file object
        # for every step from 0 to md.n_steps inclusive
        # Write the number of particles and a newline
        # And the time
        for t in range(md.n_steps+1): 
            time = t * md.time_step
            f.write("{N}\n".format(N=md.n_particles))
            f.write("time {time}\n".format(time=time))
            for i in range(md.n_particles):
                f.write("C {} {} {}\n".format(*md.xyz[t][i]))
    print("Wrote coordinates to example3d.xyz")

The `watch()` function below just lets you view your coordinate file as an animation.

In [108]:
from ase.visualize import view
from ase.io import read as ase_read

def watch(md):
    atoms = ase_read('example3d.xyz', index=':')
    view(atoms)

### Putting it all together

<div class="alert alert-block alert-info">
    <b>Write a main function that strings it all together.</b></div>

In [130]:
def main():
    md = MD3D(100)
    # setup the system
    setup_system(md)
    # for every time_step in md.n_steps, 
    # print out which step it is (so you 
    # can track your progress). Then 
    # calculate forces and integrate the 
    # equations of motion.
    for t in range(md.n_steps):
        print("Calculating time step ", t)
        get_forces(md, t)
        integrate(md, t)
    write_coordinates(md)
    # Finally, write the coordinates to a file.
    print("Done!")
    return md

## Run the code

In [131]:
sim3d = main()

[[ 0.5  0.5  0.5]
 [ 1.5  1.5  1.5]
 [ 2.5  2.5  2.5]
 [ 3.5  3.5  3.5]
 [ 4.5  4.5  4.5]
 [ 5.5  5.5  5.5]
 [ 6.5  6.5  6.5]
 [ 7.5  7.5  7.5]
 [ 8.5  8.5  8.5]
 [ 9.5  9.5  9.5]
 [10.5 10.5 10.5]
 [11.5 11.5 11.5]
 [12.5 12.5 12.5]
 [13.5 13.5 13.5]
 [14.5 14.5 14.5]
 [15.5 15.5 15.5]
 [16.5 16.5 16.5]
 [17.5 17.5 17.5]
 [18.5 18.5 18.5]
 [19.5 19.5 19.5]
 [20.5 20.5 20.5]
 [21.5 21.5 21.5]
 [22.5 22.5 22.5]
 [23.5 23.5 23.5]
 [24.5 24.5 24.5]
 [25.5 25.5 25.5]
 [26.5 26.5 26.5]
 [27.5 27.5 27.5]
 [28.5 28.5 28.5]
 [29.5 29.5 29.5]
 [30.5 30.5 30.5]
 [31.5 31.5 31.5]
 [32.5 32.5 32.5]
 [33.5 33.5 33.5]
 [34.5 34.5 34.5]
 [35.5 35.5 35.5]]
Calculating time step  0
-5.228199588082385 255.89155345693695 36
  --- Energy: 3.408821587232947 ---
Calculating time step  1
-5.229263469783052 255.89594609714945 36
  --- Energy: 3.4088530438553244 ---
Calculating time step  2
-5.232455848753768 255.89421853646448 36
  --- Energy: 3.408740372763291 ---
Calculating time step  3
-5.237774120320061 

In [132]:
watch(sim3d)

### Timing the code

<div class="alert alert-block alert-info">

<b>How long does the simulation take? Profile it with the magic command `%prun`. Which step is the least efficient? Does changing the cutoff distance help?</div>

In [137]:
%prun main()

[[ 0.5  0.5  0.5]
 [ 1.5  1.5  1.5]
 [ 2.5  2.5  2.5]
 [ 3.5  3.5  3.5]
 [ 4.5  4.5  4.5]
 [ 5.5  5.5  5.5]
 [ 6.5  6.5  6.5]
 [ 7.5  7.5  7.5]
 [ 8.5  8.5  8.5]
 [ 9.5  9.5  9.5]
 [10.5 10.5 10.5]
 [11.5 11.5 11.5]
 [12.5 12.5 12.5]
 [13.5 13.5 13.5]
 [14.5 14.5 14.5]
 [15.5 15.5 15.5]
 [16.5 16.5 16.5]
 [17.5 17.5 17.5]
 [18.5 18.5 18.5]
 [19.5 19.5 19.5]
 [20.5 20.5 20.5]
 [21.5 21.5 21.5]
 [22.5 22.5 22.5]
 [23.5 23.5 23.5]
 [24.5 24.5 24.5]
 [25.5 25.5 25.5]
 [26.5 26.5 26.5]
 [27.5 27.5 27.5]
 [28.5 28.5 28.5]
 [29.5 29.5 29.5]
 [30.5 30.5 30.5]
 [31.5 31.5 31.5]
 [32.5 32.5 32.5]
 [33.5 33.5 33.5]
 [34.5 34.5 34.5]
 [35.5 35.5 35.5]]
Calculating time step  0
-5.228199588082383 261.54225649205716 36
  --- Energy: 3.4873035738318388 ---
Calculating time step  1
-5.228735183026491 261.54333017319 36
  --- Energy: 3.4873036084324585 ---
Calculating time step  2
-5.230353056511403 261.54656908299904 36
  --- Energy: 3.487303652360781 ---
Calculating time step  3
-5.23307359134318 261

<div class="alert alert-block alert-info">

<b>How much memory is Jupyter using during the simulation? Load the `memory_profiler` extension and use `%memit` to view the peak memory consumption.

In [138]:
%load_ext memory_profiler

The memory_profiler extension is already loaded. To reload it, use:
  %reload_ext memory_profiler


In [139]:
%memit main()

[[ 0.5  0.5  0.5]
 [ 1.5  1.5  1.5]
 [ 2.5  2.5  2.5]
 [ 3.5  3.5  3.5]
 [ 4.5  4.5  4.5]
 [ 5.5  5.5  5.5]
 [ 6.5  6.5  6.5]
 [ 7.5  7.5  7.5]
 [ 8.5  8.5  8.5]
 [ 9.5  9.5  9.5]
 [10.5 10.5 10.5]
 [11.5 11.5 11.5]
 [12.5 12.5 12.5]
 [13.5 13.5 13.5]
 [14.5 14.5 14.5]
 [15.5 15.5 15.5]
 [16.5 16.5 16.5]
 [17.5 17.5 17.5]
 [18.5 18.5 18.5]
 [19.5 19.5 19.5]
 [20.5 20.5 20.5]
 [21.5 21.5 21.5]
 [22.5 22.5 22.5]
 [23.5 23.5 23.5]
 [24.5 24.5 24.5]
 [25.5 25.5 25.5]
 [26.5 26.5 26.5]
 [27.5 27.5 27.5]
 [28.5 28.5 28.5]
 [29.5 29.5 29.5]
 [30.5 30.5 30.5]
 [31.5 31.5 31.5]
 [32.5 32.5 32.5]
 [33.5 33.5 33.5]
 [34.5 34.5 34.5]
 [35.5 35.5 35.5]]
Calculating time step  0
-5.228199588082383 250.67120443242922 36
  --- Energy: 3.3363167396703397 ---
Calculating time step  1
-5.228522359760358 250.67185207200407 36
  --- Energy: 3.336316768784491 ---
Calculating time step  2
-5.229500297308137 250.6738108210502 36
  --- Energy: 3.3363168087004715 ---
Calculating time step  3
-5.23115205202625 2

[[ 0.5  0.5  0.5]
 [ 1.5  1.5  1.5]
 [ 2.5  2.5  2.5]
 [ 3.5  3.5  3.5]
 [ 4.5  4.5  4.5]
 [ 5.5  5.5  5.5]
 [ 6.5  6.5  6.5]
 [ 7.5  7.5  7.5]
 [ 8.5  8.5  8.5]
 [ 9.5  9.5  9.5]
 [10.5 10.5 10.5]
 [11.5 11.5 11.5]
 [12.5 12.5 12.5]
 [13.5 13.5 13.5]
 [14.5 14.5 14.5]
 [15.5 15.5 15.5]
 [16.5 16.5 16.5]
 [17.5 17.5 17.5]
 [18.5 18.5 18.5]
 [19.5 19.5 19.5]
 [20.5 20.5 20.5]
 [21.5 21.5 21.5]
 [22.5 22.5 22.5]
 [23.5 23.5 23.5]
 [24.5 24.5 24.5]
 [25.5 25.5 25.5]
 [26.5 26.5 26.5]
 [27.5 27.5 27.5]
 [28.5 28.5 28.5]
 [29.5 29.5 29.5]
 [30.5 30.5 30.5]
 [31.5 31.5 31.5]
 [32.5 32.5 32.5]
 [33.5 33.5 33.5]
 [34.5 34.5 34.5]
 [35.5 35.5 35.5]]
Calculating time step  0
-5.228199588082383 261.497321704209 36
  --- Energy: 3.48667947955617 ---
Calculating time step  1
-5.22874706640914 261.49841303185235 36
  --- Energy: 3.486679429153251 ---
Calculating time step  2
-5.230376211265504 261.5016684134409 36
  --- Energy: 3.486679388762637 ---
Calculating time step  3
-5.233071048628888 261.50

-9.868744010657348 270.77317560876367 36
  --- Energy: 3.486606772047902 ---
Calculating time step  95
-10.066324832686977 271.1651941958388 36
  --- Energy: 3.4865631184786787 ---
Calculating time step  96
-10.253309724073219 271.5364782690568 36
  --- Energy: 3.486525816957088 ---
Calculating time step  97
-10.405204129462609 271.8385216424227 36
  --- Energy: 3.486501574770798 ---
Calculating time step  98
-10.505161880922213 272.03800730277845 36
  --- Energy: 3.486495604735195 ---
Calculating time step  99
-10.546873924292873 272.12250426275693 36
  --- Energy: 3.4865105057523778 ---
Wrote coordinates to example3d.xyz
Done!
peak memory: 85.47 MiB, increment: 0.00 MiB


## MD analysis

### Plotting

In [4]:
import matplotlib.pyplot as plt
%matplotlib inline #magic function that displays graphs in Jupyter

Plotting is very simple if all you want is simple plots. Try plotting your total energies and temperatures over time.

In [ ]:
plt.plot(sim3d.energies_total) # avoid first entry of 0

Almost every Python plotting package is built on matplotlib, including seaborn (below). matplotlib is very powerful and flexible; unfortunately, that also makes it very finicky. Try changing the formatting below. [You can find documentation here.](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.plot.html)

In [ ]:
plt.plot(sim3d.energies_total, color='green', marker='o',
        linestyle='dashed', linewidth=2, markersize=12,
        markeredgecolor='blue', markerfacecolor='red')

Seaborn is a library with a smoother interface and documentation. [Here is an example gallery of potential plots you can make.](https://seaborn.pydata.org/examples/index.html) For now we'll make the same line plot as in matplotlib, although Seaborn requires x-values. (This may throw an error if your `energies_total` array is a different length than the number of steps).

In [ ]:
import seaborn as sns
x = list(range(sim3d.n_steps))
sns.lineplot(x, sim3d.energies_total)

One of the best parts about Seaborn is how easy it is to do statistical visualisations. Try plotting a univariate kernel density estimate:

In [ ]:
sns.kdeplot(sim1d.energies_total[1:])

Or bivariate:

In [ ]:
sns.kdeplot(sim1d.energies_total[1:], sim1d.temperatures[1:])

### Averages, standard deviations, etc

Using NumPy makes analysis much easier.

In [ ]:
sim3d.temperatures.mean()

In [ ]:
sim3d.temperatures.median()

In [ ]:
sim3d.temperatures.min()

In [ ]:
np.std(sim3d.temperatures)

In [ ]:
sim3d.temperature.sort()

## Vectorised NumPy approach

This approach is much more abstract, but gets rid of all the loops. The first step is to reshape the xyz coordinates using `ndarray.reshape()` to add an extra dimension so `row.shape` is `(1, md.n_particles, 3)`:
<img src="files/a2_row.png" width="300px">

A corresponding `col` array is created by transposing `row` such that the shape is `(md.n_particles, 1, 3)`. This is so we can broadcast the arrays with our next operation.
<img src="files/a2_col.png" width="150px">

Now, when we subtract the `col` array from the `row` array, the resulting array of displacements has the shape `(md.n_particles, md.n_particles, 3)`.

<img src="files/a2_matrix.png" width="300px">

From this displacement array the squared distance array can be calculated. Below, the subscript is the property calculated between atoms i and j in the `i:j` syntax.

<img src="files/a2_dist.png" width="300px">

Of course, the distance between atoms and themselves is 0. As the matrix is symmetric, we also need to zero the upper or lower half to avoid double-counting with `np.triu`. 

<img src="files/a2_dist_upper.png" width="300px">

The squared distance array should then be reshaped to add an extra dimension for broadcasting purposes. 

<img src="files/a2_dist_reshaped.png" width="300px">

From here energies and forces can be calculated the usual way. The function has been written below so you can compare the 1-loop implementation above to this vectorised approach. (Hopefully it works!)

In [136]:
def get_forces(md, step):
    row = md.xyz[step].reshape(1, -1, 3)
    col = row.transpose(1, 0, 2)
    
    distance = row-col #  Shape: (md.n_particles, md.n_particles, 3)
    n_cells = md.cell * np.round_(distance/md.cell)
    min_distance = distance - n_cells
    sq_dist = (min_distance ** 2).sum(axis=2)
    
    sq_dist_upper = np.triu(sq_dist)  # Setting lower triangle to 0
    # Setting any distances higher than the cutoff to 0 for convenience
    sq_dist_upper[sq_dist_upper >= md.cutoff_sq] = 0
    reshaped = sq_dist_upper.reshape(md.n_particles, md.n_particles, 1)
    
    mask = reshaped != 0
    inv_r2 = 1/reshaped[mask]
    inv_r6 = inv_r2 ** 3
    
    particle_en = 4 * inv_r6 * (inv_r6 - 1) - md.cutoff_energy
    md.energies_potential[step] = particle_en.sum()
    
    computed_force = 48 * inv_r2 * inv_r6 * (inv_r6 - 0.5)
    reshaped[mask] = computed_force
    scaled = reshaped * min_distance
    
    md.forces[step] = scaled.sum(axis=0) - scaled.sum(axis=1)
    